### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ghost** [waxnkw/gvcnn-pytorch#10]
I'm getting the IndexError in line 45 when i try to run python data_process.py. Any guess what that might be?

$ python data_process.py
Traceback (most recent call last):
  File "data_process.py", line 68, in <module>
    mk_model_net40()
  File "data_process.py", line 45, in mk_model_net40
    tmpl.append(single_path.split("obj_whiteshaded")[-2])
IndexError: list index out of range

**Comment by tony-levy** [comment]
I have the same problem

**Comment by Newcomer-Plane** [comment]
> I have the same problem

can you fix it？
